name: NtovCalc
version: '1.0.1'
main: nano.yumeko.ntovCalc.NtovCalc
api-version: '1.20'
load: STARTUP
authors: [ Qiong-Mengzi ]
description: 'Command Line Calculator'

default-permission: false
commands:
  calc:
    description: 'Compute expression.'
    usage: '/calc <expression>'
    permission-message: 'You do not have the required permissions to perform this action.'
permissions:
  calc:
    default: false
