name: NtovCalc
version: '1.0.0'
main: nano.yumeko.ntovCalc.NtovCalc
api-version: '1.20'
load: STARTUP
authors: [ Qiong-Mengzi ]
description: 'Command Line Calculator'

commands:
  calc:
    description: 'Compute expression.'
    permission: no op
    usage: '/calc <expression>'
